<?php

/**
 * @file
 * s360_layout_builder.module
 */

/**
 * Implements hook_layout_alter().
 */
function s360_layout_builder_layout_alter(&$definitions) {
  $layouts_to_hide = [
    // Remove default layout from layout_builder module.
    'layout_twocol_section',
    'layout_threecol_section',
    'layout_fourcol_section',
    // Remove default layout from layout_discovery module.
    'layout_onecol',
    'layout_twocol',
    'layout_twocol_bricks',
    'layout_threecol_25_50_25',
    'layout_threecol_33_34_33',
  ];

  foreach ($definitions as $definition) {
    if (in_array($definition->id(), $layouts_to_hide)) {
      unset($definitions[$definition->id()]);
    }
  }
}

/**
 * Implements hook_theme().
 */
function s360_layout_builder_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['paragraph__layout'] = [
    'template' => 'paragraph--layout' ,
    'base hook' => 'paragraph',
  ];

  $items['s360_layout_builder_onecol'] = [
    'template' => 's360-layout-builder--onecol',
    'render element' => 'content',
    'base hook' => 'layout',
  ];

  $items['s360_layout_builder_accordion'] = [
    'template' => 's360-layout-builder--accordion',
    'render element' => 'content',
    'base hook' => 'layout',
  ];

  $items['s360_layout_builder_twocol'] = [
    'template' => 's360-layout-builder--twocol',
    'render element' => 'content',
    'base hook' => 'layout',
  ];

  $items['s360_layout_builder_threecol'] = [
    'template' => 's360-layout-builder--threecol',
    'render element' => 'content',
    'base hook' => 'layout',
  ];

  $items['s360_layout_builder_fourcol'] = [
    'template' => 's360-layout-builder--fourcol',
    'render element' => 'content',
    'base hook' => 'layout',
  ];

  return $items;
}

/**
 * Implements hook_page_attachments_alter().
 */
function s360_layout_builder_page_attachments_alter(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 's360_layout_builder/s360_layout_builder.admin';
  }
}

/**
 * Implements hook_preprocess_paragraph() for layout.
 */
function s360_layout_builder_preprocess_paragraph__layout(&$variables) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    $elements = $variables['elements'];

    if (isset($elements['#paragraph'])) {
      /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
      $paragraph = $elements['#paragraph'];

      if ($paragraph->hasField('field_header')) {
        $field_header = $paragraph->get('field_header');

        if (!is_null($field_header->first()) && $field_header->first()->getValue()['title'] !== '') {
          if (strpos($paragraph->getBehaviorSetting('layout_paragraphs', 'layout'), 'accordion') !== FALSE) {
            $header = $field_header->first()->getValue()['title'];
          }
          else {
            $header = $field_header->view([
              'label' => 'hidden',
            ]);
          }

          $variables['content']['regions']['custom']['header'] = $header;
        }
      }
    }
  }
}
