<?php

/**
 * @file
 * s360_layout_builder.module
 */

use Drupal\Core\Cache\CacheBackendInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function s360_layout_builder_theme($existing, $type, $theme, $path) {
  $layout_paragraph_bundles = _s360_layout_builder_get_layout_paragraph_bundles();

  $layout_themes = [];

  foreach ($layout_paragraph_bundles as $layout_paragraph_bundle) {
    $layout_themes["paragraph__{$layout_paragraph_bundle}"] = [
      'template' => 'paragraph--layout' ,
      'base hook' => 'paragraph',
    ];

    $layout_themes["paragraph__{$layout_paragraph_bundle}__preview"] = [
      'template' => 'paragraph--layout--preview' ,
      'base hook' => 'paragraph',
    ];
  }

  $layouts = [
    's360_layout_builder_one_column',
    's360_layout_builder_two_column',
    's360_layout_builder_three_column',
    's360_layout_builder_four_column',
    's360_layout_builder_accordion',
    's360_layout_builder_flex',
  ];

  foreach ($layouts as $layout) {
    $layout_themes["{$layout}"] = [
      'template' => str_replace('_', '-', $layout),
      'render element' => 'content',
      'base hook' => 'layout',
    ];

    $layout_themes["{$layout}__admin"] = [
      'template' => str_replace('_', '-', "{$layout}--admin"),
      'render element' => 'content',
      'base hook' => 'layout',
    ];
  }

  return $layout_themes;
}

/**
 * Implements hook_page_attachments_alter().
 */
function s360_layout_builder_page_attachments_alter(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 's360_layout_builder/admin';
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function s360_layout_builder_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraph\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if (in_array($paragraph->getType(), _s360_layout_builder_get_layout_paragraph_bundles())) {
    _s360_layout_builder_process_layout_paragraph($variables);
  }
}

/**
 * Implements hook_modules_installed().
 */
function s360_layout_builder_modules_installed() {
  $config = \Drupal::service('config.factory')->getEditable('layout_paragraphs.settings');

  $config->set('show_paragraph_labels', 1)->save();
  $config->set('show_layout_labels', 1)->save();
}

/**
 * Implements hook_theme_suggestions_layout_alter().
 */
function s360_layout_builder_theme_suggestions_layout_alter(&$suggestions, $variables) {
  $theme = $variables['content']['#theme'];

  if (_s360_layout_builder_is_admin_route()) {
    if (str_contains($theme, 's360_layout_builder')) {
      $suggestions[] = "{$theme}__admin";
    }
  }
}

/**
 * Checks the route name to see if it's an "admin route".
 *
 * @return bool
 *   Returns true if the current route is found in the array, false otherwise.
 */
function _s360_layout_builder_is_admin_route() {
  $admin_paths = [
    'node.add',
    'entity.node.edit_form',
    'entity.group.edit_form',
    'layout_paragraphs.*',
  ];

  $url = Drupal::routeMatch()->getRouteName();

  $result = array_filter($admin_paths, function ($v) use ($url) {
    return preg_match('~' . $v . '~', $url);
  });

  return count($result) ? TRUE : FALSE;
}

/**
 * Helper function to get all paragraphs that have layout paragraphs.
 *
 * @return array
 *   An array of paragraph bundles.
 */
function _s360_layout_builder_get_layout_paragraph_bundles() {
  $cid = 's360_layout_builder:layout_paragraphs';
  $data = \Drupal::cache()->get($cid);

  if (empty($data)) {
    $paragraph_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('paragraph');

    $layout_paragraph_bundles = [];

    foreach ($paragraph_bundles as $paragraph_bundle => $paragraph_label) {
      /** @var \Drupal\paragraphs\Entity\ParagraphsType $paragraphs_type */
      $paragraphs_type = \Drupal::entityTypeManager()->getStorage('paragraphs_type')->load($paragraph_bundle);

      $layout_paragraphs_behavior = $paragraphs_type->getBehaviorPlugin('layout_paragraphs');
      $layout_paragraphs_behavior_config = $layout_paragraphs_behavior->getConfiguration();

      if (isset($layout_paragraphs_behavior_config['enabled']) && $layout_paragraphs_behavior_config['enabled']) {
        $layout_paragraph_bundles[] = $paragraph_bundle;
      }
    }

    \Drupal::cache()->set($cid, $layout_paragraph_bundles, CacheBackendInterface::CACHE_PERMANENT);
  }
  else {
    $layout_paragraph_bundles = $data->data;
  }

  return $layout_paragraph_bundles;
}

/**
 * Apply classes and additional content for a layout paragraph.
 *
 * @param array $variables
 *   The array of variables passed in from Drupal's preprocess.
 *
 * @see s360_layout_builder_preprocess_paragraph()
 */
function _s360_layout_builder_process_layout_paragraph(array &$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $paragraph_is_published = $paragraph->isPublished();

  $layout_paragraphs_layout = $paragraph->getBehaviorSetting('layout_paragraphs', 'layout');

  if (!$paragraph_is_published) {
    $variables['content']['regions']['#attributes']['data-unpublished'] = 'layout';
  }

  $variables['content']['regions']['#attributes']['id'] = 'layout-' . $paragraph->id();
  $variables['content']['regions']['#layout_tag'] = 'div';

  $field_header = $paragraph?->field_header;
  $field_header_value = $field_header?->first()?->getValue();

  if (!empty($field_header_value['title'])) {
    $variables['content']['regions']['#attributes']['class'][] = 'layout--has-header';

    if (str_contains($layout_paragraphs_layout, 'accordion')) {
      $variables['content']['regions']['#summary'] = $field_header->view([
        'type' => 's360_layout_builder_accordion_summary',
        'label' => 'hidden',
      ]);
    }
    else {
      $field_header = $field_header->view(['label' => 'hidden']);

      $variables['content']['regions']['#attributes']['aria-labelledby'] = $field_header[0]['#header_id'];
      $variables['content']['regions']['#layout_tag'] = 'section';
      $variables['content']['regions']['#header'] = $field_header;
    }
  }

  if (_s360_layout_builder_is_admin_route()) {
    if (!$paragraph_is_published) {
      $variables['attributes']['class'][] = 'paragraph--unpublished';
    }

    if ($paragraph->id()) {
      $variables['content']['layout'] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#attributes' => [
          'class' => [
            'field',
            'field--label-inline',
          ],
        ],
        'child' => [
          [
            '#type' => 'html_tag',
            '#tag' => 'div',
            '#value' => ucwords(str_replace('_', ' ', str_replace('layout_custom_', '', $layout_paragraphs_layout))),
            '#attributes' => [
              'class' => 'field__label',
            ],
          ],
          [
            '#type' => 'html_tag',
            '#tag' => 'div',
            '#value' => "(ID: #{$paragraph->id()})",
            '#attributes' => [
              'class' => 'field__item',
            ],
          ],
        ],
      ];
    }

    $layout_paragraphs_config = $paragraph->getBehaviorSetting('layout_paragraphs', 'config');

    if (isset($layout_paragraphs_config['layout'])) {
      $layout_config = (array) $layout_paragraphs_config['layout'];

      $variables['content']['layout_options'] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#attributes' => [
          'class' => 'layout-options',
        ],
        'child' => [
          [
            '#type' => 'html_tag',
            '#tag' => 'div',
            '#value' => 'Layout Options',
            '#attributes' => [
              'class' => 'layout-options__label',
            ],
          ],
        ],
      ];

      $variables['content']['layout_options']['layout_options_group'] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#attributes' => [
          'class' => 'layout-options__options-group',
        ],
      ];

      foreach ($layout_config as $layout_config_key => $layout_config_value) {
        /*
         * Patterns:
         *  layout_[*]_options
         *  layout_[one|two|three|four]_column_[*]_options
         *  layout_flex_[*]_options
         */
        preg_match('/(?:layout_(?:(?:one|two|three|four)_column_|flex_)?)(.*?)_options/', $layout_config_key, $matches);

        // When there is no layout option match or there is no value for that
        // option, move onto the next value.
        if (!$matches || !$layout_config_value[key($layout_config_value)]) {
          continue;
        }

        $variables['content']['layout_options']['layout_options_group']['field_' . $matches[1]] = [
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#attributes' => [
            'class' => 'layout-options__option',
          ],
          'child' => [
            [
              '#type' => 'html_tag',
              '#tag' => 'div',
              '#value' => ucwords(str_replace('_', ' ', $matches[1])),
              '#attributes' => [
                'class' => 'layout-options__option-label',
              ],
            ],
            [
              '#type' => 'html_tag',
              '#tag' => 'div',
              '#value' => gettype($layout_config_value[key($layout_config_value)]) == 'integer'
                ? ($layout_config_value[key($layout_config_value)]
                  ? 'true'
                  : 'false')
                : $layout_config_value[key($layout_config_value)],
              '#attributes' => [
                'class' => 'layout-options__option-value',
              ],
            ],
          ],
        ];
      }
    }

    if (isset($layout_paragraphs_config['regions'])) {
      $regions = (array) $layout_paragraphs_config['regions'];

      foreach ($regions as $region_key => $region_configs) {
        // Adds the region options at the top.
        array_unshift($variables['content']['regions'][$region_key], [
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#attributes' => [
            'class' => 'region-options',
          ],
          'child' => [
            [
              '#type' => 'html_tag',
              '#tag' => 'div',
              '#value' => 'Region Options',
              '#attributes' => [
                'class' => 'region-options__label',
              ],
            ],
          ],
        ]);

        foreach ($region_configs as $region_config_key => $region_config_value) {
          preg_match('/(?:layout_region_)(.*?)(?=_options)/', $region_config_key, $matches);

          // When there is no layout option match or there is no value for that
          // option, move onto the next value.
          if (!$matches || !$region_config_value[key($region_config_value)]) {
            continue;
          }

          $variables['content']['regions'][$region_key][0]['field_' . $matches[1]] = [
            '#type' => 'html_tag',
            '#tag' => 'div',
            '#attributes' => [
              'class' => 'region-options__option',
            ],
            'child' => [
              [
                '#type' => 'html_tag',
                '#tag' => 'div',
                '#value' => ucwords(str_replace('_', ' ', $matches[1])),
                '#attributes' => [
                  'class' => 'region-options__option-label',
                ],
              ],
              [
                '#type' => 'html_tag',
                '#tag' => 'div',
                '#value' => gettype($region_config_value[key($region_config_value)]) == 'integer'
                  ? ($region_config_value[key($region_config_value)]
                    ? 'true'
                    : 'false')
                  : $region_config_value[key($region_config_value)],
                '#attributes' => [
                  'class' => 'region-options__option-value',
                ],
              ],
            ],
          ];
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function s360_layout_builder_form_layout_paragraphs_component_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 's360_layout_builder/conditional-header-fields';
}
