<?php

/**
 * @file
 * s360_layout_builder.module
 */

/**
 * Implements hook_theme().
 */
function s360_layout_builder_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__layout' => [
      'template' => 'paragraph--layout' ,
      'base hook' => 'paragraph',
    ],
    'paragraph__layout__preview' => [
      'template' => 'paragraph--layout--preview' ,
      'base hook' => 'paragraph',
    ],
    's360_layout_builder_onecol' => [
      'template' => 's360-layout-builder--onecol',
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    's360_layout_builder_accordion' => [
      'template' => 's360-layout-builder--accordion',
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    's360_layout_builder_twocol' => [
      'template' => 's360-layout-builder--twocol',
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    's360_layout_builder_threecol' => [
      'template' => 's360-layout-builder--threecol',
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    's360_layout_builder_fourcol' => [
      'template' => 's360-layout-builder--fourcol',
      'render element' => 'content',
      'base hook' => 'layout',
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function s360_layout_builder_page_attachments_alter(array &$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 's360_layout_builder/admin';
  }
}

/**
 * Implements hook_preprocess_paragraph() for layout.
 */
function s360_layout_builder_preprocess_paragraph__layout(&$variables) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = $variables['paragraph'];

    if ($paragraph->hasField('field_header')) {
      $field_header = $paragraph->get('field_header');

      if ($field_header->title !== '') {
        if (strpos($paragraph->getBehaviorSetting('layout_paragraphs', 'layout'), 'accordion') !== FALSE) {
          $header = [
            '#type' => 'html_tag',
            '#tag' => 'span',
            '#value' => $field_header->title,
          ];
        }
        else {
          $header = $field_header->view([
            'label' => 'hidden',
          ]);
        }

        $variables['content']['regions']['header'] = $header;

        // Only add "aria-labelledby" attribute if there is an heading_id.
        if ($field_header->heading_id !== NULL) {
          $variables['content']['regions']['#attributes']['aria-labelledby'] = $field_header->heading_id;
        }
      }
    }
  }
}

/**
 * Implements hook_modules_installed().
 */
function s360_layout_builder_modules_installed() {
  $config = \Drupal::service('config.factory')->getEditable('layout_paragraphs.settings');

  $config->set('show_paragraph_labels', 1)->save();
  $config->set('show_layout_labels', 1)->save();
}
